version: 0.2

# This buildspec is intended to be run by CodePipeline builds.

env:
  secrets-manager:
    LOGIN: tfgm-br-sonarcloud-keys:sonartoken
    HOST: tfgm-br-sonarcloud-keys:HOST
    Organization: tfgm-br-sonarcloud-keys:Organization
    Project: tfgm-br-sonarcloud-keys:Project

phases:
  install:
    commands:
      # Install yarn if it wasn't already present in the build instance
      - npm install
      
  pre_build:
    commands:
      - echo "Running Sonar Cloud"

  build:
    commands:
      - echo "Running SST Build"
      - cd frontend && npm install

  post_build:
    commands:
      - echo "Running post build and tests"
